### PR TITLE
Python bindings to run dynamic graph proces from python

### PR DESCRIPTION
**Pull request by jviereck**
This implements the minimal functionality to implement a dynamic graph (control) process from pure python.

it exposes all ways to talk to the dynamic graph hardware process via shared memory. For instance, you can just read/write to the shared memory or you can also acquire the locks on the shared conditional variable. This allows you to implement different ways to control the robot.

### CODE REVIEW

**Comment by MaximilienNaveau** [comment]
CodeFactor is not so bad, it does a bit of linting and the errors are clear^^
Anyway

Why DGHeader? => SharedMemoryDirectController?

**Comment by jviereck** [comment]
It's called `DGMHead`. It's a way to control the dgm, so the head of it. `SharedMemoryDirectController` is technically correct but I find `DGMHead` cooler :)

Let me know what you want me to do here. I am fine with booth.

**Comment by MaximilienNaveau** [comment]
Ok for DGMHead

**Comment by jviereck** [comment]
I fixed the linter warning and added some documentation.

**Pull request merged**
